### ISSUE TITLE
Window offset on 49' screens

### ISSUE THREAD

**Issue by ibigbug** [DominicMaas/Tango#275]
**Describe the bug**
The window is misplaced on large screen with scaling.

**To Reproduce**

**Expected behavior**
The window should be centered or movable

**Screenshots**
<img width="805" alt="image" src="https://user-images.githubusercontent.com/543405/164390435-a38fdda6-3135-425f-9c3f-f27d4f2392b7.png">

![image](https://user-images.githubusercontent.com/543405/164390872-a0336394-41d1-4517-842c-25e818fdd523.png)

**Active DLCs**
No

**Active mods**
No

**Versions**
Type /version into the in-game chat and paste the version numbers here:
- Mod version:  latest
- Game version:  latest

**Additional context**

**Comment by Zombiextreme** [comment]
i would like to say that a 49 ft monitor would be fucking huge. i would suggest not using a cinema to play games.../s
but honestly. have you tried going through your settings and changing the display size? seems to be a game issue and not an issue with the mod itself.

**Comment by Eld0r** [comment]
You might use that on "small" gaming 4k monitors as well to be able to read. the thing is that windows scaling % stuff regardless of size and resolution fucks up the position placement. because calling the resolution function returns actual screen resolution in screen pixels but the placement is done with the windows % scaling stuff.

for example 1920*1080 screen resolution:when you place something at pos 1920/2 with scaling it uses 960 but will show at screen position 1440 (with 150% windows scaling, or exactly at the edge when using 200%) 

but all functions for placement can stay untouched when the call for screen resolution applies the zoom correction after the return. for the example of 150% scaling on fullHD divide the return values by 1.50 and store 1280*810 for resolution. then all positioning will work again. I don't know the call for a function that returns that windows zoom scale shenanigans stuff and there might already be getVirtualScreebWidth/Height (don't quote me on that name) functions which already take that into account tho.

Am 21.04.2022 11:15 schrieb Zombiextreme ***@***.***>:
i would like to say that a 49 ft monitor would be fucking huge. i would suggest not using a cinema to play games.../s

**Comment by ibigbug** [comment]
thank you guys.

looks like it requires some env setup to be able to build this project as there are some missing refs in VS.

but any pointers to code change/build steps on top of https://github.com/CitiesSkylinesMultiplayer/CSM/wiki/Developer-Resources I'm happy to make a PR or help to test.

**Comment by ibigbug** [comment]
actually found this: https://skylines-modding-docs.readthedocs.io/en/latest/modding/Getting-Started/Setting-Up-Visual-Studio.html

now I can build

**Comment by ibigbug** [comment]
I seem to have fixed it on my machine.


![image](https://user-images.githubusercontent.com/543405/164439455-7d1a4762-9655-485d-ac0c-dc010253858d.png)

**Comment by kaenganxt** [comment]
Did the issue actually occur when using the latest version from master or our latest release? It should have already been fixed on the master branch some time ago, just not released yet.

**Comment by ibigbug** [comment]
@kaenganxt you're right, master branch is working fine already - didn't know there were unreleased changes there, will close this PR.
