### ISSUE TITLE
ID Collision Error

### ISSUE THREAD

**Issue by harrison-cringe** [DominicMaas/Tango#322]
ID collision error_

**To Reproduce**
1. Go to place roads down
2. See error

**Active DLCs**
None

**Active mods**
No Extra Mods

**Versions**
Type /version into the in-game chat and paste the version numbers here:
- Mod version: 2305.270
- Game version:1.17.1-f4

**Additional context**

[log-2023-06-25.txt](https://github.com/CitiesSkylinesMultiplayer/CSM/files/11860482/log-2023-06-25.txt)

**Comment by kaenganxt** [comment]
Thanks for your report. With the information provided it is not really possible to reproduce your issue. It is definitely not happening every time you place a road, as it works fine for many other players.
For us to be able to fix your issue, please provide more details on what exactly you and the other player are doing before the issue appears. Also, please enable debug logging in the CSM in-game settings before reproducing the error and attach the new log file afterwards.

If you or the other player used the new "zone grid" settings when placing roads (left/right side only): This will be fixed in an upcoming release of CSM.

Closing this now as it is not reproducible for me, but please reopen if you want to provide further information.
